### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Beliavsky** [gklimowicz/fpp-semantics#1]
"contain" in "which contian about 370,000 lines"

In the text below, "all" not "oll" and "the" not "thi".

ALL_F
This is a list of oll Fortran files in all the fortran-examples projects.

ALL_P
This is thi list of all Fortran projects we are tracking (just based on the top-level directory names in fortran-examples).

**Comment by gklimowicz** [comment]
Thanks you for these. Mr. Dvorak and my fingers are in continuing disagreement regarding the placement of vowels on my keyboard.

**Comment by gklimowicz** [comment]
Keep those cards and letters coming!
